const dummyDoctors = [
  {
    id: 1,
    name: 'Dr. Ananya Sharma',
    specialization: 'Cardiologist',
    experience: 8,
    about: 'Heart diseases, blood pressure, chest pain, ECG',
    image: 'https://images.pexels.com/photos/32254667/pexels-photo-32254667.jpeg',
  },
  {
    id: 2,
    name: 'Dr. Rohan Mehta',
    specialization: 'Dermatologist',
    experience: 5,
    about: 'Skin, hair, acne, allergies, rashes',
    image: 'https://images.pexels.com/photos/37272297/pexels-photo-37272297.jpeg',
  },
  {
    id: 3,
    name: 'Dr. Priya Deshmukh',
    specialization: 'Pediatrician',
    experience: 10,
    about: 'Child health, vaccination, infant care',
    image: 'https://images.pexels.com/photos/36103795/pexels-photo-36103795.jpeg',
  },
  {
    id: 4,
    name: 'Dr. Arjun Patil',
    specialization: 'Orthopedic',
    experience: 6,
    about: 'Bone fractures, joint pain, arthritis, sports injury',
    image: 'https://images.pexels.com/photos/6129500/pexels-photo-6129500.jpeg',
  },
  {
    id: 5,
    name: 'Dr. Kavita Joshi',
    specialization: 'Neurologist',
    experience: 12,
    about: 'Headache, migraine, seizures, nerve disorders',
    image: 'https://images.pexels.com/photos/15752232/pexels-photo-15752232.jpeg',
  },
  {
    id: 6,
    name: 'Dr. Sanjay Kulkarni',
    specialization: 'Gastroenterologist',
    experience: 9,
    about: 'Stomach pain, acidity, digestion, liver issues',
    image: 'https://images.pexels.com/photos/6762862/pexels-photo-6762862.jpeg',
  },
  {
    id: 7,
    name: 'Dr. Meera Nair',
    specialization: 'Gynecologist',
    experience: 11,
    about: "Women's health, pregnancy care, menstrual issues",
    image: 'https://images.pexels.com/photos/7904463/pexels-photo-7904463.jpeg',
  },
  {
    id: 8,
    name: 'Dr. Vikram Singh',
    specialization: 'ENT Specialist',
    experience: 7,
    about: 'Ear, nose, throat infections, hearing issues',
    image: 'https://images.pexels.com/photos/19438558/pexels-photo-19438558.jpeg',
  },
  {
    id: 9,
    name: 'Dr. Neha Kapoor',
    specialization: 'Psychiatrist',
    experience: 8,
    about: 'Anxiety, depression, stress, sleep disorders',
    image: 'https://images.pexels.com/photos/37454250/pexels-photo-37454250.jpeg',
  },
  {
    id: 10,
    name: 'Dr. Amit Verma',
    specialization: 'Dentist',
    experience: 6,
    about: 'Toothache, cavities, gum disease, braces',
    image: 'https://images.pexels.com/photos/26886763/pexels-photo-26886763.jpeg',
  },
  {
    id: 11,
    name: 'Dr. Pooja Reddy',
    specialization: 'Ophthalmologist',
    experience: 9,
    about: 'Eye checkups, vision problems, cataract',
    image: 'https://images.pexels.com/photos/37454251/pexels-photo-37454251.jpeg',
  },
  {
    id: 12,
    name: 'Dr. Rahul Iyer',
    specialization: 'General Physician',
    experience: 14,
    about: 'Fever, cold, cough, general health checkups',
    image: 'https://images.pexels.com/photos/14438788/pexels-photo-14438788.jpeg',
  },
];

export default dummyDoctors;